spring:
  profiles:
    active: dev
  jackson:
    time-zone: Asia/Seoul
    date-format: yyyy-MM-dd HH:mm:ss
  config:
    import: optional:file:.env[.properties]
  cache:
    type: simple
  web:
    resources:
      add-mappings: false

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 8080
  application:
    name: "travel-journal-ai"

ai:
  server:
    url: https://6d016b35628b.ngrok-free.app

file:
  upload-dir: /tmp/images/

logging:
  level:
    com.travel: DEBUG