spring:
  profiles:
    active: dev
  jackson:
    time-zone: Asia/Seoul
    date-format: yyyy-MM-dd HH:mm:ss
  config:
    import: optional:file:.env[.properties]
  cache:
    type: simple
  web:
    resources:
      add-mappings: false

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 8080
  application:
    name: "travel-journal-ai"

ai:
  server:
    url: https://13b33915bc2e.ngrok-free.app

google:
  maps:
    api-key: ${MAPS_API}

file:
  upload-dir: /Users/sangmin8817/Desktop/images

logging:
  level:
    com.travel: DEBUG